config/urls.py
from django.contrib import admin
from django.urls import path, include

#Necessario para as imagens
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

#Necessario para as imagens
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
name = 'home'

urlpatterns = [
    path('', views.home_view),
    path('about', views.about_view, name='sobre'),
    path('apresentacao', views.apresentacao_view, name='apresentação'),
    path('competencias', views.competencias_view, name='competencias'),
    path('formacao', views.formacao_view, name='formação'),
    path('home', views.home_view, name='home'),
    path('index', views.index_view, name='index'),
    path('projetos', views.projetos_view, name='projetos'),
    path('blog', views.blog_view, name='blog'),
    path('nova', views.view_novo_post, name='nova'),
    path('edita/<int:post_id>', views.view_editar_post, name='edita'),
    path('apaga/<int:post_id>', views.view_apaga_post, name='apaga'),
    path('quizz', views.quizz_view, name='quizz'),
    path('programacaoWeb', views.programacaoWeb_view, name='programacaoWeb'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('apiEEI', views.API_EEI_view, name='apiEEI'),
]

portfolio/models.py
from django.db import models


# Create your models here.


class Post(models.Model):
    autor = models.CharField(max_length=100)
    data = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=200)
    descricao = models.CharField(max_length=400)
    link = models.URLField(max_length=200, blank=True)

    # imagem = models.ImageField(blank=True)

    def __str__(self):
        return f"{self.autor} no {self.data}, adicionou um {self.titulo} com a{self.descricao} e com link {self.link}"


class Quizz(models.Model):
    nome = models.CharField(max_length=50)
    pergunta1 = models.IntegerField(default=0)  # Em que ano foi criado o HTML (1991)
    pergunta2 = models.IntegerField(default=0)  # Em que ano foi criado o CSS (1994)
    pergunta3 = models.IntegerField(default=0)  # Em que ano foi criado o Python (1989)
    pergunta4 = models.CharField(max_length=50)  # O que é o Django? (framework)
    pergunta5 = models.IntegerField(default=0)  # Em que ano foi criado o Django? (2005)

    def __str__(self):
        return f"{self.nome}"


class Pessoa(models.Model):
    nome = models.CharField(max_length=100)
    link_linkedin = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.nome}"


class Projetos(models.Model):
    nome_do_projeto = models.CharField(max_length=100)
    imagem = models.ImageField(upload_to='media/', null=True)
    descricao = models.CharField(max_length=500)
    cadeira = models.CharField(max_length=100)
    ano_realizacao = models.IntegerField(default=0)
    participantes = models.ManyToManyField(Pessoa)
    link_github = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.nome_do_projeto}"


class Cadeiras(models.Model):
    nome_da_cadeira = models.CharField(max_length=100)
    semestre = models.IntegerField(default=1)
    ects = models.IntegerField(default=0)
    avaliacao = models.CharField(max_length=100, blank=True)
    link_cadeira = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.nome_da_cadeira}"


class Formacao(models.Model):
    ano = models.IntegerField(default=0)
    cadeiras = models.ManyToManyField(Cadeiras)
    total_ects = models.CharField(max_length=100)

    def __str__(self):
        return f"O {self.ano} ano tem {self.total_ects} ECTS"


class Noticias(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.CharField(max_length=400)
    imagem = models.ImageField(upload_to='media/', null=True)
    link_noticia = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return f"Noticia: {self.titulo}"


class Tecnologias(models.Model):
    nome = models.CharField(max_length=50)
    acronimo = models.CharField(max_length=20)
    ano_criacao = models.IntegerField(default=0)
    criador = models.CharField(max_length=100)
    logotipo = models.ImageField(upload_to='media/', null=True)
    link_oficial = models.URLField(max_length=200, blank=True)
    descricao = models.CharField(max_length=400)

    def __str__(self):
        return f"Tecnologia: {self.nome}"


class TrabalhosFinaisDeCurso(models.Model):
    autores = models.ManyToManyField(Pessoa, related_name='autores')
    orientadores = models.ManyToManyField(Pessoa, related_name='orientadores')
    ano = models.IntegerField(default=0)
    titulo = models.CharField(max_length=100)
    resumo = models.CharField(max_length=400)
    imagem = models.ImageField(upload_to='media/', null=True)
    relatorio = models.URLField(max_length=200, blank=True)
    link_github = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return f"Trabalho Final de Curso: {self.titulo}"

portfolio/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post
from .models import Quizz
from .models import Pessoa
from .models import Projetos
from .models import Formacao
from .models import Cadeiras
from .models import Noticias
from .models import Tecnologias
from .models import TrabalhosFinaisDeCurso


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        # ferramentas
        widgets = {
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'autor...'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'titulo...'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descricao...'}),
        }

        help_texts = {
            'autor': '↔ Insira neste campo o nome do autor',
            'titulo': '↔ Insira neste campo um titulo desejável',
            'descricao': '↔ Insira neste campo uma descrição a seu gosto',
            'link': '↔ Insira, somente se desejar, um link'
        }

        labels = {
            'autor': 'Autor',
            'titulo': 'Título',
            'descricao': 'Descrição',
            'link': 'Link que deseja inserir',
        }


class QuizzForm(ModelForm):
    class Meta:
        model = Quizz
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Insira o seu nome'}),
        }

        labels = {

            'nome': 'Qual o seu nome?',

            'pergunta1': 'Em que ano foi criado o HTML?',  # Em que ano foi criado o HTML (1991)

            'pergunta2': 'Em que ano foi criado o CSS?',  # Em que ano foi criado o CSS (1994)

            'pergunta3': 'Em que ano foi criado o Python?',  # Em que ano foi criado o Python (1989)

            'pergunta4': 'O que é o Django?',  # O que é o Django? (framework)

            'pergunta5': 'Em que ano foi criado o Django?',  # Em que ano foi criado o Django? (2005)

        }

        help_texts = {
        }


class PessoaForm(ModelForm):
    class Meta:
        model = Pessoa
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Insira o seu nome'}),
        }

        labels = {

            'nome': 'Qual o seu nome?',

            'link_linkedin': 'Se desejar, insira o seu link do linkedIn',

        }

        help_texts = {
        }


class ProjetosForm(ModelForm):
    class Meta:
        model = Projetos
        fields = '__all__'

        widgets = {
        }

        labels = {

            'imagem': 'Insira uma foto do seu projeto',

            'descricao': 'Insira a descrição do projeto',

            'cadeira': 'Qual a cadeira pertecente ao projeto',

            'ano_realizacao': 'Indique o ano de realização do projeto',

            'participantes': 'Participantes:',

            'link_github': 'Link do GitHub do projeto',

        }

        help_texts = {
        }


class FormacaoForm(ModelForm):
    class Meta:
        model = Formacao
        fields = '__all__'

        widgets = {
            'semestre': forms.NumberInput(attrs={'min': '1', 'max': '2'}),
        }

        labels = {

            'nome_da_cadeira': 'Insira o nome da cadeira',

            'semestre': 'Insira o semestre da cadeira',

            'ects': 'Indique quantos ECTS vale a cadeira',

            'avaliacao': 'Indique a sua opinião sobre a cadeira',

            'total_ects': 'Indique o total de ECTS do semestre',

            'link_cadeira': 'Indique o link da cadeira',


        }

        help_texts = {
            'avaliacao': 'Utilize entre 1 a 5 (★)',
        }


class CadeirasForm(ModelForm):
    class Meta:
        model = Cadeiras
        fields = '__all__'

        widgets = {
        }

        labels = {

            'ano': 'Insira o ano da cadeira',

            'cadeiras': 'Insira as cadeiras que pretende',

            'total_ects': 'Indique o total de ECTS do semestre',

        }

        help_texts = {
            'total_ects': 'Soma de todos os ECTS deste semestre',
        }


class NoticiasForm(ModelForm):
    class Meta:
        model = Noticias
        fields = '__all__'

        widgets = {
        }

        labels = {

            'titulo': 'Insira o titulo da noticia',

            'descricao': 'Insira o texto da noticia',

            'imagem': 'Insira a imagem da noticia',

            'link_noticia': 'Insira o link da noticia',

        }

        help_texts = {
        }


class TecnologiasForm(ModelForm):
    class Meta:
        model = Tecnologias
        fields = '__all__'

        widgets = {
        }

        labels = {

            'nome': 'Insira o nome completo da tecnologia',

            'acronimo': 'Insira o acronimo',

            'ano_criacao': 'Insira a data de criação da tecnologia',

            'criador': 'Insira o criador',

            'logotipo': 'Insira o logotipo',

            'link_oficial': 'Insira o link da pagina oficial',

            'descricao': 'Insira uma pequena descricao',

        }

        help_texts = {

        }

class TrabalhosFinaisDeCursoForm(ModelForm):
    class Meta:
        model = TrabalhosFinaisDeCurso
        fields = '__all__'

        # ferramentas
        widgets = {
        }

        labels = {
            'autores': 'Autor(es)',
            'orientadores': 'orientadores',
            'ano': 'Ano de criação do trabalho',
            'titulo': 'Título',
            'resumo': 'Insira um pequeno resumo',
            'imagem': 'Insira uma imagem do trabalho',
            'relatorio': 'Insira o link do relatorio',
            'link_github': 'Insira o link do github',
        }

        help_texts = {
        }

portfolio/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
import datetime
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
from .forms import PostForm
from .models import Post
from .models import Quizz
from .forms import Projetos
from .forms import QuizzForm
from .forms import Formacao
from .forms import Noticias
from .forms import Tecnologias
from .forms import TrabalhosFinaisDeCurso

from .funcoesQuizz import desenha_grafico_resultados


def about_view(request):
    return render(request, 'portfolio/about.html')


def apresentacao_view(request):
    return render(request, 'portfolio/apresentação.html')


def competencias_view(request):
    return render(request, 'portfolio/competencias.html')


def formacao_view(request):
    context = {'formacao': Formacao.objects.all(), 'cadeiras': Formacao.cadeiras}

    return render(request, 'portfolio/formação.html', context)


def home_view(request):
    agora = datetime.datetime.now()

    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }

    return render(request, 'portfolio/home.html', context)


def index_view(request):
    return render(request, 'portfolio/layout.html')


def programacaoWeb_view(request):
    context = {'noticias': Noticias.objects.all(), 'tecnologias': Tecnologias.objects.all()}

    return render(request, 'portfolio/programacaoWeb.html', context)


def projetos_view(request):
    context = {'projetos': Projetos.objects.all(),
               'pessoa': Projetos.participantes,
               'tfc': TrabalhosFinaisDeCurso.objects.all(),
               'tfc_autores': TrabalhosFinaisDeCurso.autores,
               'tfc_orientadores': TrabalhosFinaisDeCurso.orientadores,
               }

    return render(request, 'portfolio/projetos.html', context)


def blog_view(request):
    context = {'post': Post.objects.all()}

    return render(request, 'portfolio/blog.html', context)


def API_EEI_view(request):

    return render(request, 'portfolio/estacaoEspacialEEI.html')


def login_view(request):
    if request.method == "POST":
        nome_login = request.POST.get('username')
        password_login = request.POST.get('password')
        utilizador = authenticate(request, username=nome_login, password=password_login)

        if utilizador is not None:
            login(request, utilizador)
            context = {'post': Post.objects.all()}
            return render(request, 'portfolio/blog.html', context)
        else:
            return render(
                request, 'portfolio/login.html',
                {'message': "Credenciais Invalidas"}
            )

    return render(request, 'portfolio/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'portfolio/login.html')


# PÁGINA DO QUIZZ
def quizz_view(request):
    desenha_grafico_resultados(Quizz.objects.all())

    form = QuizzForm(request.POST, use_required_attribute=False)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(request.path_info)

    context = {
        'form': form,
    }

    return render(request, 'portfolio/quizz.html', context)


# PÁGINAS DO BLOG
def view_novo_post(request):
    form = PostForm(request.POST or None)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form}
    return render(request, 'portfolio/nova.html', context)


@login_required
def view_editar_post(request, post_id):
    post = Post.objects.get(id=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'post_id': post_id}
    return render(request, 'portfolio/edita.html', context)


@login_required
def view_apaga_post(request, post_id):
    Post.objects.get(id=post_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))

portfolio/templates/portfolio/about.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/about.css' %}"/>

{% endblock style %}


{% block main %}

<div class="container">
    <div class="divRetangulos">

        <div class="textoDentroDivRetangulos">

            <h3> <u> Ricardo Cleto</u> 👋🏼 </h3>

            <img src="../static/portfolio/images/Ricardo.jpg" alt="ERROR">

            <p class="transfFormacao">
                Olá, o meu nome é Ricardo, sou aluno do 2º ano e estou a estudar
                <a href="{% url 'portfolio:formação'%}"> Engenharia Informática na Universidade Lusófona</a>.
            </p>

            <br>

            <p class="transfFormacao">
                Já joguei Semi-Profissionalmente CS:GO (Counter-Strike: Global Offensive) pela equipa Oro Esports e
                representei a equipa em torneios online
            </p>

            <br>

            <p>
                 Estudei em várias escolas presentes no Agrupamento de Escolas de Sampaio:
            </p>

            <li>➥ Escola Básica de Sampaio</li>
            <li>➥ Escola Secundária de Sampaio</li>

            <br>

            <p>
                <span class="spanTitleColor">Apdidões:</span>
                <li> Linguagens de Programação:</li>
            </p>

            <p class="skills">
                <li> ➥ Java </li>
                <li> ➥ Kotlin </li>
                <li> ➥ C </li>
                <li> ➥ C# </li>
                <li> ➥ Python </li>
            </p>

            <br>

            <p>
                <span class="spanTitleColor">Competências:</span>
            </p>


            <p class="skills">
                <li> ➥ Social Skills </li>
                <li> ➥ Trabalhos em Grupo </li>
                <li> ➥ Criativo </li>
                <li> ➥ Motivacional </li>
                <li> ➥ 2 Línguas (Idiomas): Português (Nativo) , Inglês (Fluente) </li>
            </p>

            <p class="Socials">
                <span class="spanTitleColor"> Contact me here: </span>
                <a href="https://www.linkedin.com/in/ricardo-cleto-8114b5208/"> LinkedIn  </a>
                <span class="divisoria"> | </span>
                <a href="https://github.com/ricardocleto22006526">GitHub</a>
                <span class="divisoria"> | </span>
                <a href="../../static/portfolio/images/CV.png" target="_blank">Verifique o meu CV</a>
                <span class="divisoria"> | </span>
                <a class="NoClass">Email: a22006526@alunos.ulht.pt</a>
            </p>

        </div>

         <center>
            <iframe src="https://www.youtube.com/embed/3a86iwzRSHc" title="Video de Apresentação" ></iframe>
         </center>

    </div>
</div>

{% endblock main %}

portfolio/templates/portfolio/apresentação.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/apresentacao.css' %}"/>

{% endblock style %}


{% block main %}

<div class="container">


</div>

{% endblock main %}

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/blog.css' %}"/>

{% endblock style %}

{% block main %}

<div class="container">
    <div class="divRetangulos">

        <a href="{% url 'portfolio:nova' %}" class="btnCriaPost" >Criar Post</a>

        {% for posts in post %}

            <div>

                <!--- ><p>ID: {{posts.id}}</p> --->

                <p>{{posts.autor}}</p>

                <p>{{posts.titulo}}</p>

                <p>{{posts.descricao}}</p>

                <br>
                {% if posts.link %}
                    <p>Link: <a href="{{posts.link}}">{{posts.link}}</a></p>
                {% endif %}

                <p>Data: {{posts.data}}</p>

                {% if not user.is_authenticated %}
                    <a href="{% url 'portfolio:login' %}" class="logar">Logue para realizar alterações</a>
                {% endif %}

                {% if user.is_authenticated %}
                    <a href="{% url 'portfolio:edita' posts.id %}" class="editar">Editar</a> <a href="{% url 'portfolio:apaga' posts.id %}" class="apagar">Apagar</a>
                {% endif %}


            </div>

        {% endfor %}

    </div>
</div>


{% endblock main %}

portfolio/templates/portfolio/competencias.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/competencias.css' %}"/>

{% endblock style %}


{% block main %}

<div class="container">


</div>

{% endblock main %}

portfolio/templates/portfolio/edita.html
{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/edita.css' %}"/>

{% endblock style %}

{% block main %}

<div class="container">
    <div class="divRetangulos">
        <div>
            <h3>Edite o seu Post!!!</h3>
            <br><br><br>

            <form action="{% url 'portfolio:edita' post_id %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <a href="{% url 'portfolio:blog' %}" role="button" class="btnCancel">Cancelar</a>
                <input type="submit" value="Gravar" class="btnSubmit">
            </form>
        </div>
    </div>
</div>



{% endblock %}

portfolio/templates/portfolio/estacaoEspacialEEI.html
<link href="https://fonts.googleapis.com/css2?family=Secular+One&display=swap" rel="stylesheet">


{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/layout.css' %}"/>


 <header class="header1">
    <div class="hero">
        <nav>
            <h2 class="logo">Ricardo <span>Cleto</span></h2>
            <ul>
                <li> <a href="{% url 'portfolio:home' %}">Home</a> </li>
                <li> <a href="{% url 'portfolio:programacaoWeb' %}">ProgramaçãoWeb</a> </li>
                <li> <a href="{% url 'portfolio:quizz' %}">Quizz</a> </li>
                <li> <a href="{% url 'portfolio:formação' %}">Formação</a> </li>
                <li> <a href="{% url 'portfolio:projetos' %}">Projetos</a> </li>
                <li> <a href="{% url 'portfolio:blog' %}">Blog</a> </li>
                    <li> <a href="{% url 'portfolio:apiEEI' %}">API(EEI)</a> </li>
                <li> <a href="{% url 'portfolio:sobre' %}">About Me</a> </li>
            </ul>
                {% if not user.is_authenticated %}
            <a href="{% url 'portfolio:login' %}" class="btn">Login</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a href="{% url 'portfolio:logout' %}" class="btnLogout">Logout</a>
            {% endif %}
        </nav>
     </div>
 </header>



{% block head %}

    <link
      rel="stylesheet"
      href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
      integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
      crossorigin=""
    />
    <script
      src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
      integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
      crossorigin=""
    ></script>

{% endblock head %}



{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/estacaoEspacialEEI.css' %}"/>

{% endblock style %}


{% block main %}
    <div class="container">

        <h1 class="tituloAPI"> Real Time tracking </h1>
        <h2 class="SubtituloAPI">🛰️ Estação Espacial Internacional 🛰️</h2>

        <p>
          latitude: <span id="lat"></span>°<br />
          longitude: <span id="lon"></span>° <br />
        </p>

        <div id="issMap"></div>
    </div>
{% endblock main %}



{% block script %}
    <script>

        // construcao do mapa
        const mymap = L.map('issMap').setView([0, 0], 1.5); // Coordenadas: x=0,y=0 & zoom=2


       // Adição dos 2 links de direitos de autor (Sites "Originais")
        const attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';
        const tileUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
        const tiles = L.tileLayer(tileUrl, { attribution });
        tiles.addTo(mymap)


        // Icon do satelite
        const issIcon = L.icon({

            iconUrl: '../static/portfolio/images/EEI.png',
            iconSize: [75, 48],
            iconAnchor: [37.5, 24]

        });


        // Marcador = Ponto central localizador do Satelite
        let marker = L.marker([0, 0], { icon: issIcon }).addTo(mymap);


        // Guardamos o link da API
        const api_url = 'https://api.wheretheiss.at/v1/satellites/25544';


        // Funcao que trabalha os dados da API
        async function getISS() {
            // Chamar a API atraves do Fetch
            const response = await fetch(api_url);

            // Obter os dados da API
            const data = await response.json();

            // Metodo que guarda os dados nas 2 variaveis criadas
            const { latitude, longitude } = data;

            // Colocar sempre visão e zoom nas coordenadas correspondentes ao satelite
            mymap.setView([latitude, longitude], mymap.getZoom());
            marker.setLatLng([latitude, longitude]);

            // Variaveis informativas com 2 casa decimais
            document.getElementById('lat').textContent = latitude.toFixed(2);
            document.getElementById('lon').textContent = longitude.toFixed(2);
        }


        //Chamamos a funcao que gera tudo e atualizamos os dados de 1 em 1 segundo
        getISS();
        setInterval(getISS, 1000);
    </script>
{% endblock script %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>

    <link href="https://fonts.googleapis.com/css2?family=Secular+One&display=swap" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/layout.css' %}"/>

    {% block style %}{% endblock style %}

     <script>

        function startTime() {

          let clock = document.getElementById('time');

          clock.innerHTML = new Date().toLocaleTimeString();

          setTimeout(startTime, 1000);
        }

     </script>

</head>

<body onload="startTime()">

    <!--- TASK BAR COMUM A TODOS OS FICHEIROS--->
    <header class="header1">
        <div class="hero">
            <nav>
                <h2 class="logo">Ricardo <span>Cleto</span></h2>

                <ul>
                    <li> <a href="{% url 'portfolio:home' %}">Home</a> </li>
                    <li> <a href="{% url 'portfolio:programacaoWeb' %}">ProgramaçãoWeb</a> </li>
                    <li> <a href="{% url 'portfolio:quizz' %}">Quizz</a> </li>
                    <li> <a href="{% url 'portfolio:formação' %}">Formação</a> </li>
                    <li> <a href="{% url 'portfolio:projetos' %}">Projetos</a> </li>
                    <li> <a href="{% url 'portfolio:blog' %}">Blog</a> </li>
                    <li> <a href="{% url 'portfolio:apiEEI' %}">API(EEI)</a> </li>
                    <li> <a href="{% url 'portfolio:sobre' %}">About Me</a> </li>
                </ul>

                {% if not user.is_authenticated %}
                    <a href="{% url 'portfolio:login' %}" class="btn">Login</a>
                {% endif %}

                {% if user.is_authenticated %}
                    <a href="{% url 'portfolio:logout' %}" class="btnLogout">Logout</a>
                {% endif %}

            </nav>
        </div>
    </header>
    <!---
    <header class="header">
        <div>
            <h1>Ricardo Cleto </h1>
        </div>

        <nav>
            <a href="{% url 'portfolio:index' %}">Página Inicial</a>

            <a href="{% url 'portfolio:home' %}">Home</a>
            <a href="{% url 'portfolio:apresentação' %}">Apresentação</a>
            <a href="{% url 'portfolio:competencias' %}">Competencias</a>
            <a href="{% url 'portfolio:formação' %}">Formação</a>
            <a href="{% url 'portfolio:projetos' %}">Projetos</a>
            <a href="{% url 'portfolio:sobre' %}">About</a>
        </nav>
    </header>

    -->

	<main>

        {% block main %}

        {% endblock main %}
    </main>


    <footer>
        <div class="footerBackground">
            <div style="margin-left: 10%;">ULHT 2022 ©</div>
            <div id="time" style="margin-left: 10%;"></div>
        </div>
    </footer>

</body>


</html>

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}

{% block style %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/login.css' %}"/>

{% endblock style %}

{% block main %}

<div class="container">
    <div class="divRetangulos">
        <div>
            <h3>Realize o seu login</h3>
            <br><br><br>

            <form action="{% url 'portfolio:login' %}" method="post">
                {% csrf_token %}

                <p>Introduza o seu username: <input type="text" name="username" placeholder="Username"></p>
                <p>Introduza a sua password: <input type="password" name="password" placeholder="Password"></p>

                <input type="submit" value="Entrar!" class="btnSubmit">
            </form>
            {% if message %}
                {{ message }}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}